service: quaesta
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-prune-plugin
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline-sns
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"
  dynamodb:
    stages:
      - ${opt:stage, self:provider.stage}
    start:
      port: 8080
      inMemory: false
      migrate: true
  serverless-offline:
    httpPort: 8000
    websocketPort: 8001
    lambdaPort: 8002
    useWorkerThreads: true
  serverless-offline-sns:
    port: 4002
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    required:
      env:
        - AWS_REGION
        - MAIL_USERNAME
        - MAIL_PASSWORD
        - TWITCH_CLIENT_ID
        - TWITCH_CLIENT_SECRET

provider:
  name: aws
  stage: prod
  runtime: nodejs14.x
  region: ${env:AWS_REGION}
  logs:
    websocket: true

functions:
  graphql:
    description: GraphQL API
    handler: lambda/graphql/index.graphql
    events:
      - http:
          path: /graphql
          method: post
          cors: true
  socketSubscribe:
    description: Websocket Subscription Handler
    handler: lambda/subscription/subscribe.subscribe
    events:
      - websocket: $connect
      - websocket: $default
  snsRecieve:
    description: SNS Recieve Handler
    handler: lambda/subscription/publish.publish
    events:
      - sns:
          topicName: subscription

package:
  patterns:
    - schema.graphql
    - frontend/static

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: email
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: username
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    sockets:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sockets
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
          - AttributeName: operationId
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: operationId
            AttributeType: S
          - AttributeName: subscription
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: subscription
            KeySchema:
              - AttributeName: subscription
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
